SalesforceFiles/retrieveOutput/objects/App__c.object
<CustomObject>
    <description>Database table that stores information on apps</description>
    <label>App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/objects/Attribute__c.object
<CustomObject>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <referenceTo>Event__c</referenceTo>
        <relationshipLabel>Attributes</relationshipLabel>
        <relationshipName>Attributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/objects/Event__c.object
<CustomObject>
    <fields>
        <fullName>EventName__c</fullName>
        <label>EventName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session__c</fullName>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Events</relationshipLabel>
        <relationshipName>Events</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>App__c</fullName>
        <label>App</label>
        <referenceTo>App__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/classes/PieGraphCreator.cls
/**
 * PieGraphCreator
 * Graph request handler for a pie graph
 */
public class PieGraphCreator extends GraphCreator {
    
    public PieGraphCreator(){}
    
    //see documentation for this method in GraphCreator
    public override Datatable createJSDataTable(GraphRequest requestedGraph){
        
        List<Datatable.Column> tableColumns = new List<Datatable.Column>();
        tableColumns.add(new Datatable.Column('vals', 'string', 'Device Object'));
        tableColumns.add(new Datatable.Column('counts', 'num', 'count'));
        Datatable table = new Datatable(tableColumns);
        
        String appName = requestedGraph.getAppName();
        String firstEventName = requestedGraph.getFirstAttribEvent();
        String firstAttribName = requestedGraph.getFirstAttrib();
        
        List<AggregateResult> sessions;
        if(firstEventName == null || firstEventName == '')
        {
            String soqlQuery = 'SELECT ' + firstAttribName + ' value , COUNT(Id) theCount '
                             + 'FROM Session__c s '
                             + 'WHERE s.App__r.Name = \'' + appName + '\' '
                             + 'GROUP BY ' + firstAttribName;
            
            sessions = Database.query(soqlQuery);
        }
        else
        {
            sessions = [SELECT a.value__c value, COUNT(Id) theCount 
                        FROM  Attribute__c a
                        WHERE a.Event__r.Session__r.App__r.Name = :appName
                          AND a.Event__r.EventName__c = :firstEventName
                          AND a.key__c = :firstAttribName
                        GROUP BY a.value__c];
        }
                                          
        for(AggregateResult result : sessions){
            List<Object> cellVals = new List<Object>();
            Object sliceName = result.get('value');
            Object count = result.get('theCount');
            if(sliceName instanceof String && count instanceof Integer){
                
                cellVals.add(sliceName);
                cellVals.add(count);
                table.addRow(cellVals);
            }
        }
        
        System.debug(JSON.serialize(table));
        return table; 
    }
}