SalesforceFiles/retrieveOutput/objects/App__c.object
<CustomObject>
    <description>Database table that stores information on apps</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PackageName__c</fullName>
        <description>Name of the package in which the user&apos;s app is being developed.</description>
        <label>PackageName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version__c</fullName>
        <description>The string name of the version of the current app.</description>
        <label>Version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/classes/AppRestResource.cls
@RestResource(urlMapping='/channel4_apps/*')

global class AppRestResource 
{
    @HttpGet
    global static String getRelatedApps()
    {
        List<AggregateResult> appList = [SELECT Label__c, PackageName__c, Version__c FROM App__c GROUP BY Label__c, PackageName__c, Version__c];
        
        JSONGenerator gen = JSON.createGenerator(true);
        
        gen.writeStartArray();
        for(AggregateResult a : appList)
        {
            gen.writeStartObject();
            gen.writeStringField('Label__c', (String)a.get('Label__c'));
            gen.writeStringField('PackageName__c', (String)a.get('PackageName__c'));
            gen.writeStringField('Version__c', (String)a.get('Version__c'));
            gen.writeEndObject();
        }
        gen.writeEndArray();
        
        return gen.getAsString();
        
        //return JSON.serializePretty(appList);
    }
}