SalesforceFiles/retrieveOutput/objects/App__c.object
<CustomObject>
    <description>Database table that stores information on apps</description>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>App</label>
    <nameField>
        <label>App Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>App__c</fullName>
        <label>App</label>
        <referenceTo>App__c</referenceTo>
        <relationshipLabel>Sessions</relationshipLabel>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DeviceCountry__c</fullName>
        <description>Country Code</description>
        <label>DeviceCountry</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceFiles/retrieveOutput/classes/GeochartGraphCreator.cls
public class GeochartGraphCreator extends GraphCreator
{
    private GeochartGraphRequest request;
    
    public GeochartGraphCreator(GeochartGraphRequest request)
    {
        this.request = request;
    }
    
    public override Datatable createJSDataTable()
    {
        List<Datatable.Column> tableColumns = new List<Datatable.Column>();
        tableColumns.add(new Datatable.Column('Country', 'string', 'Country'));
        tableColumns.add(new Datatable.Column('Popularity', 'number', 'Popularity'));
        Datatable table = new Datatable(tableColumns);
        String appLabel = request.getAppLabel();
        
        List<AggregateResult> soqlResult = [SELECT DeviceCountry__c Country, COUNT(Id) CountryCount 
                                            FROM Session__c s
                                            WHERE App__r.Label__c = :appLabel
                                            GROUP BY DeviceCountry__c];
        
        for(AggregateResult result : soqlResult)
        {
            List<Object> cellVals = new List<Object>();
            Object country = result.get('Country');
            Object countryCount = result.get('CountryCount');
            if(country instanceof String && countryCount instanceof Integer)
            {    
                cellVals.add(country);
                cellVals.add(countryCount);
                table.addRow(cellVals);
            }
        }
        
        System.debug(JSON.serialize(table));
        return table;
    }
}